language: erlang
otp_release:
  - 17.3
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.2.zip
  - unzip -d elixir v1.0.2.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix deps.get
script:
  - MIX_ENV=test mix test
notifications:
  recipients:
    - nizar.venturini@gmail.com
